services:

    backend:
        image: node_backend:1 # providing a name for the image, giving it a tag for the version
        container_name: ${SERVER_HOST} # providing a name for the container
        build: 
            context: . # providing the path of where it can find the Dockerfile
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - ${NODE_PORT}:${NODE_PORT}
        volumes:
            - .:/app # here, /app is being linked with the current local folder
            - node_backend_modules:/app/node_modules # here, node_modules refer to the persistent volume node_modules, given at the bottom of the file. It will contains the node modules persistently
        # command: 
        #     npm run dev
        #     npm run start
        depends_on:
            - database

    database:
        image: mongo_database:1 # providing a name for the image, giving it a tag for the version
        container_name: ${DATABASE_HOST}
        build: 
            context: database/
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        volumes:
            - mongo_data:/data/db

# persistent volumes that will be kept when running docker compose up again
volumes:
    mongo_data:
    node_backend_modules: